name: Run Test with Percy
on:
  push:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1.0.0
      - name: Install dependencies for percy tests
        run: npm install
      - name: Percy Test with master branch
        uses: percy/exec-action@v0.3.0
        if: github.ref == 'refs/heads/master'
        with:
          command: "node snapshots.js PERCY_BRANCH=master"
          working-directory: ./percy-tests
          verbose: true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
      - name: Percy Test with develop branch
        uses: percy/exec-action@v0.3.0
        if: github.ref == 'refs/heads/develop'
        with:
          command: "node snapshots.js PERCY_BRANCH=develop PERCY_TARGET_BRANCH=master"
          working-directory: ./percy-tests
          verbose: true
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
